// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeFactorsOfCitizen = `-- name: ActiveFactorsOfCitizen :many
SELECT id, citizen_id, factor_type, status, totp_secret_enc, passkey_credential_id, passkey_public_key, biometric_embedding_enc, enrolled_at, last_used_at, revoked_at FROM mfa_factor WHERE citizen_id = $1 AND status = 'active' ORDER BY enrolled_at, id
`

func (q *Queries) ActiveFactorsOfCitizen(ctx context.Context, citizenID pgtype.UUID) ([]MfaFactor, error) {
	rows, err := q.db.Query(ctx, activeFactorsOfCitizen, citizenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaFactor{}
	for rows.Next() {
		var i MfaFactor
		if err := rows.Scan(
			&i.ID,
			&i.CitizenID,
			&i.FactorType,
			&i.Status,
			&i.TotpSecretEnc,
			&i.PasskeyCredentialID,
			&i.PasskeyPublicKey,
			&i.BiometricEmbeddingEnc,
			&i.EnrolledAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByAccessHash = `-- name: FindSessionByAccessHash :one
SELECT id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at FROM session WHERE access_token_hash = $1
`

func (q *Queries) FindSessionByAccessHash(ctx context.Context, accessTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByAccessHash, accessTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionByRefreshHash = `-- name: FindSessionByRefreshHash :one
SELECT id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at FROM session WHERE refresh_token_hash = $1
`

func (q *Queries) FindSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at FROM session WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthEvent = `-- name: InsertAuthEvent :one
INSERT INTO auth_event (id, citizen_id, session_id, event_type, factor_type, ip_address, device_fingerprint, anomaly_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, citizen_id, session_id, event_type, factor_type, ip_address, device_fingerprint, anomaly_reason, created_at
`

type InsertAuthEventParams struct {
	ID                pgtype.UUID `json:"id"`
	CitizenID         pgtype.UUID `json:"citizen_id"`
	SessionID         pgtype.UUID `json:"session_id"`
	EventType         string      `json:"event_type"`
	FactorType        pgtype.Text `json:"factor_type"`
	IpAddress         pgtype.Text `json:"ip_address"`
	DeviceFingerprint pgtype.Text `json:"device_fingerprint"`
	AnomalyReason     pgtype.Text `json:"anomaly_reason"`
}

func (q *Queries) InsertAuthEvent(ctx context.Context, arg InsertAuthEventParams) (AuthEvent, error) {
	row := q.db.QueryRow(ctx, insertAuthEvent,
		arg.ID,
		arg.CitizenID,
		arg.SessionID,
		arg.EventType,
		arg.FactorType,
		arg.IpAddress,
		arg.DeviceFingerprint,
		arg.AnomalyReason,
	)
	var i AuthEvent
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.SessionID,
		&i.EventType,
		&i.FactorType,
		&i.IpAddress,
		&i.DeviceFingerprint,
		&i.AnomalyReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertMfaFactor = `-- name: InsertMfaFactor :one
INSERT INTO mfa_factor (id, citizen_id, factor_type, status, totp_secret_enc, passkey_credential_id, passkey_public_key, biometric_embedding_enc, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, citizen_id, factor_type, status, totp_secret_enc, passkey_credential_id, passkey_public_key, biometric_embedding_enc, enrolled_at, last_used_at, revoked_at
`

type InsertMfaFactorParams struct {
	ID                    pgtype.UUID        `json:"id"`
	CitizenID             pgtype.UUID        `json:"citizen_id"`
	FactorType            string             `json:"factor_type"`
	Status                string             `json:"status"`
	TotpSecretEnc         pgtype.Text        `json:"totp_secret_enc"`
	PasskeyCredentialID   pgtype.Text        `json:"passkey_credential_id"`
	PasskeyPublicKey      pgtype.Text        `json:"passkey_public_key"`
	BiometricEmbeddingEnc pgtype.Text        `json:"biometric_embedding_enc"`
	LastUsedAt            pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) InsertMfaFactor(ctx context.Context, arg InsertMfaFactorParams) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, insertMfaFactor,
		arg.ID,
		arg.CitizenID,
		arg.FactorType,
		arg.Status,
		arg.TotpSecretEnc,
		arg.PasskeyCredentialID,
		arg.PasskeyPublicKey,
		arg.BiometricEmbeddingEnc,
		arg.LastUsedAt,
	)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.FactorType,
		&i.Status,
		&i.TotpSecretEnc,
		&i.PasskeyCredentialID,
		&i.PasskeyPublicKey,
		&i.BiometricEmbeddingEnc,
		&i.EnrolledAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO session (id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at
`

type InsertSessionParams struct {
	ID                pgtype.UUID        `json:"id"`
	CitizenID         pgtype.UUID        `json:"citizen_id"`
	AccessTokenHash   string             `json:"access_token_hash"`
	RefreshTokenHash  string             `json:"refresh_token_hash"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	DeviceFingerprint string             `json:"device_fingerprint"`
	IpSubnet          string             `json:"ip_subnet"`
	AssuranceTier     string             `json:"assurance_tier"`
	LastMfaAt         pgtype.Timestamptz `json:"last_mfa_at"`
	LastRefreshAt     pgtype.Timestamptz `json:"last_refresh_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
}

// Auth queries (TBL-037…039). Refresh rotation retires hashes into the
// Go-side reuse set (best-effort replay detection); MFA failure windows are
// tracked the same way. Both are documented in pgStore.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.CitizenID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.DeviceFingerprint,
		arg.IpSubnet,
		arg.AssuranceTier,
		arg.LastMfaAt,
		arg.LastRefreshAt,
		arg.ExpiresAt,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthEvents = `-- name: ListAuthEvents :many
SELECT id, citizen_id, session_id, event_type, factor_type, ip_address, device_fingerprint, anomaly_reason, created_at FROM auth_event ORDER BY created_at, id
`

func (q *Queries) ListAuthEvents(ctx context.Context) ([]AuthEvent, error) {
	rows, err := q.db.Query(ctx, listAuthEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthEvent{}
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.CitizenID,
			&i.SessionID,
			&i.EventType,
			&i.FactorType,
			&i.IpAddress,
			&i.DeviceFingerprint,
			&i.AnomalyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitizenAuthEvents = `-- name: ListCitizenAuthEvents :many
SELECT id, citizen_id, session_id, event_type, factor_type, ip_address, device_fingerprint, anomaly_reason, created_at FROM auth_event WHERE citizen_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCitizenAuthEvents(ctx context.Context, citizenID pgtype.UUID) ([]AuthEvent, error) {
	rows, err := q.db.Query(ctx, listCitizenAuthEvents, citizenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthEvent{}
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.CitizenID,
			&i.SessionID,
			&i.EventType,
			&i.FactorType,
			&i.IpAddress,
			&i.DeviceFingerprint,
			&i.AnomalyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM session WHERE status <> 'revoked' AND expires_at < $1
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllCitizenSessions = `-- name: RevokeAllCitizenSessions :execrows
UPDATE session SET status = 'revoked' WHERE citizen_id = $1 AND status <> 'revoked'
`

func (q *Queries) RevokeAllCitizenSessions(ctx context.Context, citizenID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllCitizenSessions, citizenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeMfaFactor = `-- name: RevokeMfaFactor :one
UPDATE mfa_factor SET status = 'revoked', revoked_at = $3
WHERE id = $1 AND citizen_id = $2
RETURNING id, citizen_id, factor_type, status, totp_secret_enc, passkey_credential_id, passkey_public_key, biometric_embedding_enc, enrolled_at, last_used_at, revoked_at
`

type RevokeMfaFactorParams struct {
	ID        pgtype.UUID        `json:"id"`
	CitizenID pgtype.UUID        `json:"citizen_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeMfaFactor(ctx context.Context, arg RevokeMfaFactorParams) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, revokeMfaFactor, arg.ID, arg.CitizenID, arg.RevokedAt)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.FactorType,
		&i.Status,
		&i.TotpSecretEnc,
		&i.PasskeyCredentialID,
		&i.PasskeyPublicKey,
		&i.BiometricEmbeddingEnc,
		&i.EnrolledAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const rotateSessionAccess = `-- name: RotateSessionAccess :one
UPDATE session
SET access_token_hash = $2, access_expires_at = $3
WHERE id = $1
RETURNING id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at
`

type RotateSessionAccessParams struct {
	ID              pgtype.UUID        `json:"id"`
	AccessTokenHash string             `json:"access_token_hash"`
	AccessExpiresAt pgtype.Timestamptz `json:"access_expires_at"`
}

func (q *Queries) RotateSessionAccess(ctx context.Context, arg RotateSessionAccessParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionAccess, arg.ID, arg.AccessTokenHash, arg.AccessExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const rotateSessionTokens = `-- name: RotateSessionTokens :one
UPDATE session
SET access_token_hash = $2, refresh_token_hash = $3, access_expires_at = $4, last_refresh_at = $5
WHERE id = $1
RETURNING id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at
`

type RotateSessionTokensParams struct {
	ID               pgtype.UUID        `json:"id"`
	AccessTokenHash  string             `json:"access_token_hash"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	LastRefreshAt    pgtype.Timestamptz `json:"last_refresh_at"`
}

func (q *Queries) RotateSessionTokens(ctx context.Context, arg RotateSessionTokensParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionTokens,
		arg.ID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.LastRefreshAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const sessionsOfCitizen = `-- name: SessionsOfCitizen :many
SELECT id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at FROM session WHERE citizen_id = $1 ORDER BY created_at, id
`

func (q *Queries) SessionsOfCitizen(ctx context.Context, citizenID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionsOfCitizen, citizenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CitizenID,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.AccessExpiresAt,
			&i.DeviceFingerprint,
			&i.IpSubnet,
			&i.AssuranceTier,
			&i.LastMfaAt,
			&i.LastRefreshAt,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionStatus = `-- name: SetSessionStatus :one
UPDATE session SET status = $2 WHERE id = $1
RETURNING id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at
`

type SetSessionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setSessionTier = `-- name: SetSessionTier :one
UPDATE session SET assurance_tier = $2, last_mfa_at = $3 WHERE id = $1
RETURNING id, citizen_id, access_token_hash, refresh_token_hash, access_expires_at, device_fingerprint, ip_subnet, assurance_tier, last_mfa_at, last_refresh_at, expires_at, status, created_at
`

type SetSessionTierParams struct {
	ID            pgtype.UUID        `json:"id"`
	AssuranceTier string             `json:"assurance_tier"`
	LastMfaAt     pgtype.Timestamptz `json:"last_mfa_at"`
}

func (q *Queries) SetSessionTier(ctx context.Context, arg SetSessionTierParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionTier, arg.ID, arg.AssuranceTier, arg.LastMfaAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CitizenID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.DeviceFingerprint,
		&i.IpSubnet,
		&i.AssuranceTier,
		&i.LastMfaAt,
		&i.LastRefreshAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const touchMfaFactor = `-- name: TouchMfaFactor :exec
UPDATE mfa_factor SET last_used_at = $2 WHERE id = $1
`

type TouchMfaFactorParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchMfaFactor(ctx context.Context, arg TouchMfaFactorParams) error {
	_, err := q.db.Exec(ctx, touchMfaFactor, arg.ID, arg.LastUsedAt)
	return err
}
