// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConstitutionalRight = `-- name: CreateConstitutionalRight :one
INSERT INTO constitutional_right (id, name, description, protected)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, protected
`

type CreateConstitutionalRightParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Protected   bool        `json:"protected"`
}

func (q *Queries) CreateConstitutionalRight(ctx context.Context, arg CreateConstitutionalRightParams) (ConstitutionalRight, error) {
	row := q.db.QueryRow(ctx, createConstitutionalRight,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Protected,
	)
	var i ConstitutionalRight
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Protected,
	)
	return i, err
}

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT seq, id, action_type, actor_ref, payload_hash, prev_hash, signature, idempotency_key, created_at FROM audit_log WHERE id = $1
`

func (q *Queries) GetAuditEntry(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, id)
	var i AuditLog
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ActionType,
		&i.ActorRef,
		&i.PayloadHash,
		&i.PrevHash,
		&i.Signature,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditTip = `-- name: GetAuditTip :one

SELECT payload_hash FROM audit_log ORDER BY seq DESC LIMIT 1
`

// Audit queries (TBL-034…036). The chain trigger enforces prev_hash on
// insert; writers serialize on an advisory lock in Go (pgStore) so
// concurrent appends cannot interleave tips.
func (q *Queries) GetAuditTip(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAuditTip)
	var payload_hash string
	err := row.Scan(&payload_hash)
	return payload_hash, err
}

const getEntryByIdempotencyKey = `-- name: GetEntryByIdempotencyKey :one
SELECT seq, id, action_type, actor_ref, payload_hash, prev_hash, signature, idempotency_key, created_at FROM audit_log WHERE idempotency_key = $1
`

func (q *Queries) GetEntryByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getEntryByIdempotencyKey, idempotencyKey)
	var i AuditLog
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ActionType,
		&i.ActorRef,
		&i.PayloadHash,
		&i.PrevHash,
		&i.Signature,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getProtocolChange = `-- name: GetProtocolChange :one
SELECT id, change_ref, required_approval_refs, approvals, delay_until, visible_since, status, created_at, released_at FROM protocol_change WHERE id = $1
`

func (q *Queries) GetProtocolChange(ctx context.Context, id pgtype.UUID) (ProtocolChange, error) {
	row := q.db.QueryRow(ctx, getProtocolChange, id)
	var i ProtocolChange
	err := row.Scan(
		&i.ID,
		&i.ChangeRef,
		&i.RequiredApprovalRefs,
		&i.Approvals,
		&i.DelayUntil,
		&i.VisibleSince,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_log (id, action_type, actor_ref, payload_hash, prev_hash, signature, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING seq, id, action_type, actor_ref, payload_hash, prev_hash, signature, idempotency_key, created_at
`

type InsertAuditEntryParams struct {
	ID             pgtype.UUID `json:"id"`
	ActionType     string      `json:"action_type"`
	ActorRef       string      `json:"actor_ref"`
	PayloadHash    string      `json:"payload_hash"`
	PrevHash       string      `json:"prev_hash"`
	Signature      string      `json:"signature"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditEntry,
		arg.ID,
		arg.ActionType,
		arg.ActorRef,
		arg.PayloadHash,
		arg.PrevHash,
		arg.Signature,
		arg.IdempotencyKey,
	)
	var i AuditLog
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ActionType,
		&i.ActorRef,
		&i.PayloadHash,
		&i.PrevHash,
		&i.Signature,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertConstitutionalReview = `-- name: InsertConstitutionalReview :one
INSERT INTO constitutional_review (id, proposal_id, right_id, result, reviewer_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, proposal_id, right_id, result, reviewer_ref, created_at
`

type InsertConstitutionalReviewParams struct {
	ID          pgtype.UUID `json:"id"`
	ProposalID  pgtype.UUID `json:"proposal_id"`
	RightID     pgtype.UUID `json:"right_id"`
	Result      string      `json:"result"`
	ReviewerRef string      `json:"reviewer_ref"`
}

func (q *Queries) InsertConstitutionalReview(ctx context.Context, arg InsertConstitutionalReviewParams) (ConstitutionalReview, error) {
	row := q.db.QueryRow(ctx, insertConstitutionalReview,
		arg.ID,
		arg.ProposalID,
		arg.RightID,
		arg.Result,
		arg.ReviewerRef,
	)
	var i ConstitutionalReview
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.RightID,
		&i.Result,
		&i.ReviewerRef,
		&i.CreatedAt,
	)
	return i, err
}

const insertProtocolChange = `-- name: InsertProtocolChange :one

INSERT INTO protocol_change (id, change_ref, required_approval_refs, approvals, delay_until, visible_since, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, change_ref, required_approval_refs, approvals, delay_until, visible_since, status, created_at, released_at
`

type InsertProtocolChangeParams struct {
	ID                   pgtype.UUID        `json:"id"`
	ChangeRef            string             `json:"change_ref"`
	RequiredApprovalRefs []string           `json:"required_approval_refs"`
	Approvals            []byte             `json:"approvals"`
	DelayUntil           pgtype.Timestamptz `json:"delay_until"`
	VisibleSince         pgtype.Timestamptz `json:"visible_since"`
	Status               string             `json:"status"`
}

// Protocol change gate (DP-043).
func (q *Queries) InsertProtocolChange(ctx context.Context, arg InsertProtocolChangeParams) (ProtocolChange, error) {
	row := q.db.QueryRow(ctx, insertProtocolChange,
		arg.ID,
		arg.ChangeRef,
		arg.RequiredApprovalRefs,
		arg.Approvals,
		arg.DelayUntil,
		arg.VisibleSince,
		arg.Status,
	)
	var i ProtocolChange
	err := row.Scan(
		&i.ID,
		&i.ChangeRef,
		&i.RequiredApprovalRefs,
		&i.Approvals,
		&i.DelayUntil,
		&i.VisibleSince,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const listAllReviews = `-- name: ListAllReviews :many
SELECT id, proposal_id, right_id, result, reviewer_ref, created_at FROM constitutional_review ORDER BY created_at, id
`

func (q *Queries) ListAllReviews(ctx context.Context) ([]ConstitutionalReview, error) {
	rows, err := q.db.Query(ctx, listAllReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstitutionalReview{}
	for rows.Next() {
		var i ConstitutionalReview
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.RightID,
			&i.Result,
			&i.ReviewerRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT seq, id, action_type, actor_ref, payload_hash, prev_hash, signature, idempotency_key, created_at FROM audit_log ORDER BY seq LIMIT NULLIF($1, 0)
`

func (q *Queries) ListAuditEntries(ctx context.Context, dollar_1 interface{}) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ActionType,
			&i.ActorRef,
			&i.PayloadHash,
			&i.PrevHash,
			&i.Signature,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstitutionalRights = `-- name: ListConstitutionalRights :many
SELECT id, name, description, protected FROM constitutional_right ORDER BY id
`

func (q *Queries) ListConstitutionalRights(ctx context.Context) ([]ConstitutionalRight, error) {
	rows, err := q.db.Query(ctx, listConstitutionalRights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstitutionalRight{}
	for rows.Next() {
		var i ConstitutionalRight
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocolChanges = `-- name: ListProtocolChanges :many
SELECT id, change_ref, required_approval_refs, approvals, delay_until, visible_since, status, created_at, released_at FROM protocol_change ORDER BY created_at, id
`

func (q *Queries) ListProtocolChanges(ctx context.Context) ([]ProtocolChange, error) {
	rows, err := q.db.Query(ctx, listProtocolChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProtocolChange{}
	for rows.Next() {
		var i ProtocolChange
		if err := rows.Scan(
			&i.ID,
			&i.ChangeRef,
			&i.RequiredApprovalRefs,
			&i.Approvals,
			&i.DelayUntil,
			&i.VisibleSince,
			&i.Status,
			&i.CreatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProposal = `-- name: ListReviewsByProposal :many
SELECT id, proposal_id, right_id, result, reviewer_ref, created_at FROM constitutional_review WHERE proposal_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListReviewsByProposal(ctx context.Context, proposalID pgtype.UUID) ([]ConstitutionalReview, error) {
	rows, err := q.db.Query(ctx, listReviewsByProposal, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstitutionalReview{}
	for rows.Next() {
		var i ConstitutionalReview
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.RightID,
			&i.Result,
			&i.ReviewerRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProtocolChange = `-- name: UpdateProtocolChange :one
UPDATE protocol_change SET approvals = $2, status = $3, released_at = $4
WHERE id = $1
RETURNING id, change_ref, required_approval_refs, approvals, delay_until, visible_since, status, created_at, released_at
`

type UpdateProtocolChangeParams struct {
	ID         pgtype.UUID        `json:"id"`
	Approvals  []byte             `json:"approvals"`
	Status     string             `json:"status"`
	ReleasedAt pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) UpdateProtocolChange(ctx context.Context, arg UpdateProtocolChangeParams) (ProtocolChange, error) {
	row := q.db.QueryRow(ctx, updateProtocolChange,
		arg.ID,
		arg.Approvals,
		arg.Status,
		arg.ReleasedAt,
	)
	var i ProtocolChange
	err := row.Scan(
		&i.ID,
		&i.ChangeRef,
		&i.RequiredApprovalRefs,
		&i.Approvals,
		&i.DelayUntil,
		&i.VisibleSince,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}
