// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegation.sql

package delegationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDelegation = `-- name: CreateDelegation :one

INSERT INTO delegation (id, delegator_id, delegate_id, domain_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, delegator_id, delegate_id, domain_id, created_at, expires_at, revoked_at
`

type CreateDelegationParams struct {
	ID          pgtype.UUID        `json:"id"`
	DelegatorID pgtype.UUID        `json:"delegator_id"`
	DelegateID  pgtype.UUID        `json:"delegate_id"`
	DomainID    pgtype.UUID        `json:"domain_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Delegation queries (TBL-023). Cycle detection walks active edges in Go
// (pgStore) from ListActiveDomainEdges, mirroring the in-memory store.
func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, createDelegation,
		arg.ID,
		arg.DelegatorID,
		arg.DelegateID,
		arg.DomainID,
		arg.ExpiresAt,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.DelegatorID,
		&i.DelegateID,
		&i.DomainID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const expireDueDelegations = `-- name: ExpireDueDelegations :many
UPDATE delegation SET revoked_at = $1
WHERE expires_at <= $1 AND revoked_at IS NULL
RETURNING id, delegator_id, delegate_id, domain_id, created_at, expires_at, revoked_at
`

func (q *Queries) ExpireDueDelegations(ctx context.Context, revokedAt pgtype.Timestamptz) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, expireDueDelegations, revokedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.DelegatorID,
			&i.DelegateID,
			&i.DomainID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelegation = `-- name: GetDelegation :one
SELECT id, delegator_id, delegate_id, domain_id, created_at, expires_at, revoked_at FROM delegation WHERE id = $1
`

func (q *Queries) GetDelegation(ctx context.Context, id pgtype.UUID) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegation, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.DelegatorID,
		&i.DelegateID,
		&i.DomainID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveDomainEdges = `-- name: ListActiveDomainEdges :many
SELECT delegator_id, delegate_id FROM delegation
WHERE domain_id = $1 AND revoked_at IS NULL AND expires_at > $2
`

type ListActiveDomainEdgesParams struct {
	DomainID  pgtype.UUID        `json:"domain_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ListActiveDomainEdgesRow struct {
	DelegatorID pgtype.UUID `json:"delegator_id"`
	DelegateID  pgtype.UUID `json:"delegate_id"`
}

func (q *Queries) ListActiveDomainEdges(ctx context.Context, arg ListActiveDomainEdgesParams) ([]ListActiveDomainEdgesRow, error) {
	rows, err := q.db.Query(ctx, listActiveDomainEdges, arg.DomainID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDomainEdgesRow{}
	for rows.Next() {
		var i ListActiveDomainEdgesRow
		if err := rows.Scan(&i.DelegatorID, &i.DelegateID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDelegations = `-- name: ListAllDelegations :many
SELECT id, delegator_id, delegate_id, domain_id, created_at, expires_at, revoked_at FROM delegation ORDER BY created_at, id
`

func (q *Queries) ListAllDelegations(ctx context.Context) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listAllDelegations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delegation{}
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.DelegatorID,
			&i.DelegateID,
			&i.DomainID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDelegation = `-- name: RevokeDelegation :one
UPDATE delegation SET revoked_at = GREATEST($2, created_at) WHERE id = $1
RETURNING id, delegator_id, delegate_id, domain_id, created_at, expires_at, revoked_at
`

type RevokeDelegationParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// GREATEST keeps the revoked_at >= created_at invariant under app/DB clock
// differences: revocation is effective immediately either way, and a
// backdated revocation can never be recorded.
func (q *Queries) RevokeDelegation(ctx context.Context, arg RevokeDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, revokeDelegation, arg.ID, arg.RevokedAt)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.DelegatorID,
		&i.DelegateID,
		&i.DomainID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
