// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package delegationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	Seq            int64              `json:"seq"`
	ID             pgtype.UUID        `json:"id"`
	ActionType     string             `json:"action_type"`
	ActorRef       string             `json:"actor_ref"`
	PayloadHash    string             `json:"payload_hash"`
	PrevHash       string             `json:"prev_hash"`
	Signature      string             `json:"signature"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthEvent struct {
	ID                pgtype.UUID        `json:"id"`
	CitizenID         pgtype.UUID        `json:"citizen_id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	EventType         string             `json:"event_type"`
	FactorType        pgtype.Text        `json:"factor_type"`
	IpAddress         pgtype.Text        `json:"ip_address"`
	DeviceFingerprint pgtype.Text        `json:"device_fingerprint"`
	AnomalyReason     pgtype.Text        `json:"anomaly_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Ballot struct {
	ID               pgtype.UUID        `json:"id"`
	VoteSessionID    pgtype.UUID        `json:"vote_session_id"`
	TokenBlind       string             `json:"token_blind"`
	EncryptedChoice  string             `json:"encrypted_choice"`
	VerificationCode string             `json:"verification_code"`
	CastAt           pgtype.Timestamptz `json:"cast_at"`
}

type ConstitutionalReview struct {
	ID          pgtype.UUID        `json:"id"`
	ProposalID  pgtype.UUID        `json:"proposal_id"`
	RightID     pgtype.UUID        `json:"right_id"`
	Result      string             `json:"result"`
	ReviewerRef string             `json:"reviewer_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConstitutionalRight struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Protected   bool        `json:"protected"`
}

type Delegation struct {
	ID          pgtype.UUID        `json:"id"`
	DelegatorID pgtype.UUID        `json:"delegator_id"`
	DelegateID  pgtype.UUID        `json:"delegate_id"`
	DomainID    pgtype.UUID        `json:"domain_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type EligibilityToken struct {
	ID               pgtype.UUID        `json:"id"`
	VoteSessionID    pgtype.UUID        `json:"vote_session_id"`
	CitizenID        pgtype.UUID        `json:"citizen_id"`
	BlindedTokenHash string             `json:"blinded_token_hash"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	Used             bool               `json:"used"`
}

type MfaFactor struct {
	ID                    pgtype.UUID        `json:"id"`
	CitizenID             pgtype.UUID        `json:"citizen_id"`
	FactorType            string             `json:"factor_type"`
	Status                string             `json:"status"`
	TotpSecretEnc         pgtype.Text        `json:"totp_secret_enc"`
	PasskeyCredentialID   pgtype.Text        `json:"passkey_credential_id"`
	PasskeyPublicKey      pgtype.Text        `json:"passkey_public_key"`
	BiometricEmbeddingEnc pgtype.Text        `json:"biometric_embedding_enc"`
	EnrolledAt            pgtype.Timestamptz `json:"enrolled_at"`
	LastUsedAt            pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
}

type ProtocolChange struct {
	ID                   pgtype.UUID        `json:"id"`
	ChangeRef            string             `json:"change_ref"`
	RequiredApprovalRefs []string           `json:"required_approval_refs"`
	Approvals            []byte             `json:"approvals"`
	DelayUntil           pgtype.Timestamptz `json:"delay_until"`
	VisibleSince         pgtype.Timestamptz `json:"visible_since"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ReleasedAt           pgtype.Timestamptz `json:"released_at"`
}

type Session struct {
	ID                pgtype.UUID        `json:"id"`
	CitizenID         pgtype.UUID        `json:"citizen_id"`
	AccessTokenHash   string             `json:"access_token_hash"`
	RefreshTokenHash  string             `json:"refresh_token_hash"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	DeviceFingerprint string             `json:"device_fingerprint"`
	IpSubnet          string             `json:"ip_subnet"`
	AssuranceTier     string             `json:"assurance_tier"`
	LastMfaAt         pgtype.Timestamptz `json:"last_mfa_at"`
	LastRefreshAt     pgtype.Timestamptz `json:"last_refresh_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type VoteOption struct {
	ID            pgtype.UUID `json:"id"`
	VoteSessionID pgtype.UUID `json:"vote_session_id"`
	ProposalID    pgtype.UUID `json:"proposal_id"`
	Label         string      `json:"label"`
	Description   string      `json:"description"`
}

type VoteSession struct {
	ID               pgtype.UUID        `json:"id"`
	ProposalID       pgtype.UUID        `json:"proposal_id"`
	JurisdictionID   pgtype.UUID        `json:"jurisdiction_id"`
	Method           string             `json:"method"`
	ThresholdRule    string             `json:"threshold_rule"`
	MinParticipation pgtype.Numeric     `json:"min_participation"`
	CoolingOffUntil  pgtype.Timestamptz `json:"cooling_off_until"`
	OpensAt          pgtype.Timestamptz `json:"opens_at"`
	ClosesAt         pgtype.Timestamptz `json:"closes_at"`
	Status           string             `json:"status"`
	TallyResult      []byte             `json:"tally_result"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
