// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voting.sql

package votingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessionTokens = `-- name: CountSessionTokens :one
SELECT count(*) FROM eligibility_token WHERE vote_session_id = $1
`

func (q *Queries) CountSessionTokens(ctx context.Context, voteSessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionTokens, voteSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoteOption = `-- name: CreateVoteOption :one
INSERT INTO vote_option (id, vote_session_id, proposal_id, label, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vote_session_id, proposal_id, label, description
`

type CreateVoteOptionParams struct {
	ID            pgtype.UUID `json:"id"`
	VoteSessionID pgtype.UUID `json:"vote_session_id"`
	ProposalID    pgtype.UUID `json:"proposal_id"`
	Label         string      `json:"label"`
	Description   string      `json:"description"`
}

func (q *Queries) CreateVoteOption(ctx context.Context, arg CreateVoteOptionParams) (VoteOption, error) {
	row := q.db.QueryRow(ctx, createVoteOption,
		arg.ID,
		arg.VoteSessionID,
		arg.ProposalID,
		arg.Label,
		arg.Description,
	)
	var i VoteOption
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.ProposalID,
		&i.Label,
		&i.Description,
	)
	return i, err
}

const createVoteSession = `-- name: CreateVoteSession :one

INSERT INTO vote_session (id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status, tally_result, created_at
`

type CreateVoteSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	ProposalID       pgtype.UUID        `json:"proposal_id"`
	JurisdictionID   pgtype.UUID        `json:"jurisdiction_id"`
	Method           string             `json:"method"`
	ThresholdRule    string             `json:"threshold_rule"`
	MinParticipation pgtype.Numeric     `json:"min_participation"`
	CoolingOffUntil  pgtype.Timestamptz `json:"cooling_off_until"`
	OpensAt          pgtype.Timestamptz `json:"opens_at"`
	ClosesAt         pgtype.Timestamptz `json:"closes_at"`
	Status           string             `json:"status"`
}

// Voting queries (TBL-019…022). Atomic multi-step writes (DP-016 cast) are
// orchestrated in Go transactions (pgStore) from these primitives.
func (q *Queries) CreateVoteSession(ctx context.Context, arg CreateVoteSessionParams) (VoteSession, error) {
	row := q.db.QueryRow(ctx, createVoteSession,
		arg.ID,
		arg.ProposalID,
		arg.JurisdictionID,
		arg.Method,
		arg.ThresholdRule,
		arg.MinParticipation,
		arg.CoolingOffUntil,
		arg.OpensAt,
		arg.ClosesAt,
		arg.Status,
	)
	var i VoteSession
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.JurisdictionID,
		&i.Method,
		&i.ThresholdRule,
		&i.MinParticipation,
		&i.CoolingOffUntil,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Status,
		&i.TallyResult,
		&i.CreatedAt,
	)
	return i, err
}

const getBallotByVerification = `-- name: GetBallotByVerification :one
SELECT id, vote_session_id, token_blind, encrypted_choice, verification_code, cast_at FROM ballot WHERE verification_code = $1
`

func (q *Queries) GetBallotByVerification(ctx context.Context, verificationCode string) (Ballot, error) {
	row := q.db.QueryRow(ctx, getBallotByVerification, verificationCode)
	var i Ballot
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.TokenBlind,
		&i.EncryptedChoice,
		&i.VerificationCode,
		&i.CastAt,
	)
	return i, err
}

const getEligibilityToken = `-- name: GetEligibilityToken :one
SELECT id, vote_session_id, citizen_id, blinded_token_hash, issued_at, used FROM eligibility_token WHERE id = $1
`

func (q *Queries) GetEligibilityToken(ctx context.Context, id pgtype.UUID) (EligibilityToken, error) {
	row := q.db.QueryRow(ctx, getEligibilityToken, id)
	var i EligibilityToken
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.CitizenID,
		&i.BlindedTokenHash,
		&i.IssuedAt,
		&i.Used,
	)
	return i, err
}

const getTokenBySessionCitizen = `-- name: GetTokenBySessionCitizen :one
SELECT id, vote_session_id, citizen_id, blinded_token_hash, issued_at, used FROM eligibility_token WHERE vote_session_id = $1 AND citizen_id = $2
`

type GetTokenBySessionCitizenParams struct {
	VoteSessionID pgtype.UUID `json:"vote_session_id"`
	CitizenID     pgtype.UUID `json:"citizen_id"`
}

func (q *Queries) GetTokenBySessionCitizen(ctx context.Context, arg GetTokenBySessionCitizenParams) (EligibilityToken, error) {
	row := q.db.QueryRow(ctx, getTokenBySessionCitizen, arg.VoteSessionID, arg.CitizenID)
	var i EligibilityToken
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.CitizenID,
		&i.BlindedTokenHash,
		&i.IssuedAt,
		&i.Used,
	)
	return i, err
}

const getVoteSession = `-- name: GetVoteSession :one
SELECT id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status, tally_result, created_at FROM vote_session WHERE id = $1
`

func (q *Queries) GetVoteSession(ctx context.Context, id pgtype.UUID) (VoteSession, error) {
	row := q.db.QueryRow(ctx, getVoteSession, id)
	var i VoteSession
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.JurisdictionID,
		&i.Method,
		&i.ThresholdRule,
		&i.MinParticipation,
		&i.CoolingOffUntil,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Status,
		&i.TallyResult,
		&i.CreatedAt,
	)
	return i, err
}

const insertBallot = `-- name: InsertBallot :one
INSERT INTO ballot (id, vote_session_id, token_blind, encrypted_choice, verification_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vote_session_id, token_blind, encrypted_choice, verification_code, cast_at
`

type InsertBallotParams struct {
	ID               pgtype.UUID `json:"id"`
	VoteSessionID    pgtype.UUID `json:"vote_session_id"`
	TokenBlind       string      `json:"token_blind"`
	EncryptedChoice  string      `json:"encrypted_choice"`
	VerificationCode string      `json:"verification_code"`
}

func (q *Queries) InsertBallot(ctx context.Context, arg InsertBallotParams) (Ballot, error) {
	row := q.db.QueryRow(ctx, insertBallot,
		arg.ID,
		arg.VoteSessionID,
		arg.TokenBlind,
		arg.EncryptedChoice,
		arg.VerificationCode,
	)
	var i Ballot
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.TokenBlind,
		&i.EncryptedChoice,
		&i.VerificationCode,
		&i.CastAt,
	)
	return i, err
}

const insertEligibilityToken = `-- name: InsertEligibilityToken :one
INSERT INTO eligibility_token (id, vote_session_id, citizen_id, blinded_token_hash, used)
VALUES ($1, $2, $3, $4, FALSE)
ON CONFLICT (vote_session_id, citizen_id) DO NOTHING
RETURNING id, vote_session_id, citizen_id, blinded_token_hash, issued_at, used
`

type InsertEligibilityTokenParams struct {
	ID               pgtype.UUID `json:"id"`
	VoteSessionID    pgtype.UUID `json:"vote_session_id"`
	CitizenID        pgtype.UUID `json:"citizen_id"`
	BlindedTokenHash string      `json:"blinded_token_hash"`
}

func (q *Queries) InsertEligibilityToken(ctx context.Context, arg InsertEligibilityTokenParams) (EligibilityToken, error) {
	row := q.db.QueryRow(ctx, insertEligibilityToken,
		arg.ID,
		arg.VoteSessionID,
		arg.CitizenID,
		arg.BlindedTokenHash,
	)
	var i EligibilityToken
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.CitizenID,
		&i.BlindedTokenHash,
		&i.IssuedAt,
		&i.Used,
	)
	return i, err
}

const listSessionBallots = `-- name: ListSessionBallots :many
SELECT id, vote_session_id, token_blind, encrypted_choice, verification_code, cast_at FROM ballot WHERE vote_session_id = $1 ORDER BY cast_at, id
`

func (q *Queries) ListSessionBallots(ctx context.Context, voteSessionID pgtype.UUID) ([]Ballot, error) {
	rows, err := q.db.Query(ctx, listSessionBallots, voteSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ballot{}
	for rows.Next() {
		var i Ballot
		if err := rows.Scan(
			&i.ID,
			&i.VoteSessionID,
			&i.TokenBlind,
			&i.EncryptedChoice,
			&i.VerificationCode,
			&i.CastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteOptions = `-- name: ListVoteOptions :many
SELECT id, vote_session_id, proposal_id, label, description FROM vote_option WHERE vote_session_id = $1 ORDER BY id
`

func (q *Queries) ListVoteOptions(ctx context.Context, voteSessionID pgtype.UUID) ([]VoteOption, error) {
	rows, err := q.db.Query(ctx, listVoteOptions, voteSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoteOption{}
	for rows.Next() {
		var i VoteOption
		if err := rows.Scan(
			&i.ID,
			&i.VoteSessionID,
			&i.ProposalID,
			&i.Label,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteSessions = `-- name: ListVoteSessions :many
SELECT id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status, tally_result, created_at FROM vote_session ORDER BY created_at, id
`

func (q *Queries) ListVoteSessions(ctx context.Context) ([]VoteSession, error) {
	rows, err := q.db.Query(ctx, listVoteSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoteSession{}
	for rows.Next() {
		var i VoteSession
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.JurisdictionID,
			&i.Method,
			&i.ThresholdRule,
			&i.MinParticipation,
			&i.CoolingOffUntil,
			&i.OpensAt,
			&i.ClosesAt,
			&i.Status,
			&i.TallyResult,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEligibilityToken = `-- name: LockEligibilityToken :one
SELECT id, vote_session_id, citizen_id, blinded_token_hash, issued_at, used FROM eligibility_token WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEligibilityToken(ctx context.Context, id pgtype.UUID) (EligibilityToken, error) {
	row := q.db.QueryRow(ctx, lockEligibilityToken, id)
	var i EligibilityToken
	err := row.Scan(
		&i.ID,
		&i.VoteSessionID,
		&i.CitizenID,
		&i.BlindedTokenHash,
		&i.IssuedAt,
		&i.Used,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE eligibility_token SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}

const setVoteSessionTally = `-- name: SetVoteSessionTally :one
UPDATE vote_session SET tally_result = $2 WHERE id = $1
RETURNING id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status, tally_result, created_at
`

type SetVoteSessionTallyParams struct {
	ID          pgtype.UUID `json:"id"`
	TallyResult []byte      `json:"tally_result"`
}

func (q *Queries) SetVoteSessionTally(ctx context.Context, arg SetVoteSessionTallyParams) (VoteSession, error) {
	row := q.db.QueryRow(ctx, setVoteSessionTally, arg.ID, arg.TallyResult)
	var i VoteSession
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.JurisdictionID,
		&i.Method,
		&i.ThresholdRule,
		&i.MinParticipation,
		&i.CoolingOffUntil,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Status,
		&i.TallyResult,
		&i.CreatedAt,
	)
	return i, err
}

const updateVoteSessionStatus = `-- name: UpdateVoteSessionStatus :one
UPDATE vote_session SET status = $2 WHERE id = $1
RETURNING id, proposal_id, jurisdiction_id, method, threshold_rule, min_participation, cooling_off_until, opens_at, closes_at, status, tally_result, created_at
`

type UpdateVoteSessionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateVoteSessionStatus(ctx context.Context, arg UpdateVoteSessionStatusParams) (VoteSession, error) {
	row := q.db.QueryRow(ctx, updateVoteSessionStatus, arg.ID, arg.Status)
	var i VoteSession
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.JurisdictionID,
		&i.Method,
		&i.ThresholdRule,
		&i.MinParticipation,
		&i.CoolingOffUntil,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Status,
		&i.TallyResult,
		&i.CreatedAt,
	)
	return i, err
}
